# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
# Adapted from: https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/ci.yaml
name: Lint charm

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Check linting and formatting
        run: make check

  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - uses: terraform-linters/setup-tflint@v4
      - run: make terraform-check-all
