# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
# Adapted from: https://github.com/canonical/postgresql-operator/blob/main/.github/workflows/ci.yaml
name: Unit test charm

concurrency:
  group: unit-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_call:

jobs:
  charm-unit-test:
    name: Unit test charm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run tests
        run: make test

  terraform-unit-test:
    name: Terraform unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.10"

      - name: Run terraform tests
        run: make terraform-test-all
